{{- if .Values.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qentra-agent.fullname" . }}
  labels:
    {{- include "qentra-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.token | quote }}
{{- end }}
